### ISSUE TITLE
Hardware connections?

### ISSUE THREAD

**Issue by mungewell** [vorwieger/modular-link#1]
Looks like a great little project... commit messages mention using an encoder.

Can you please detail how you are wiring this (and maybe some buttons) to the Pi.
Thanks,
Simon.

**Comment by codenuts42** [comment]
Hello @mungewell, 
I uploaded a [wiring schematic](https://github.com/vorwieger/modular-link/blob/master/doc/schema.pdf). If you have any questions, I will try to answer.
Peter
